id: P001784
initial_creation_type: ocr
source_metadata:
  id: bdr:W30147
  title: ཀློང་བརྡོལ་ངག་དབང་བློ་བཟང་དཔལ་བཟང་པོའི་རྣམ་ཐར་མོས་གུས་རིན་ཆེན་འདྲེན་པའི་ཤིང་རྟ་རྒྱལ་སྲས་སྤྱོད་རྒྱན།
  author: ''
  volumes:
    0a574149d9a5413bae66661457912cbc:
      image_group_id: I1KG12965
      title: ''
      volume_number: 1
      total_pages: 400
      base_file: v001.txt
