id: P001784
initial_creation_type: ocr
source_metadata:
  id: bdr:W30147
  title: ཀློང་བརྡོལ་ངག་དབང་བློ་བཟང་དཔལ་བཟང་པོའི་རྣམ་ཐར་མོས་གུས་རིན་ཆེན་འདྲེན་པའི་ཤིང་རྟ་རྒྱལ་སྲས་སྤྱོད་རྒྱན།
  author: ''
  volumes: {}
