id: I89E28DFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T17:51:29+00:00'
last_modified: '2022-06-07T15:08:23.388517+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30147
  title: ཀློང་བརྡོལ་ངག་དབང་བློ་བཟང་དཔལ་བཟང་པོའི་རྣམ་ཐར་མོས་གུས་རིན་ཆེན་འདྲེན་པའི་ཤིང་རྟ་རྒྱལ་སྲས་སྤྱོད་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7D60:
      image_group_id: I1KG12965
      title: ''
      total_pages: 400
      order: 1
      base_file: 7D60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
